server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bysj_english?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true

#    url: jdbc:mysql://localhost:3306/bysj_english?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true